### ISSUE TITLE
Can't set game path

### ISSUE THREAD

**Issue by tian-li** [palexdev/ENBManager#1]
**Describe the bug**
The button to select game path does not respond. And can't type the path in the text box neither. 

**To Reproduce**
This happens on first open of this tool and click the game icon in the top left corner of main window

**Expected behavior**
Open a window to select path of game

**Screenshots**
![image](https://github.com/palexdev/ENBManager/assets/11455447/b2f336df-cc16-4745-93cf-8a42ebcb26cb)

**Desktop (please complete the following information):**
 - OS: Window 10 22H2 build 19045.3086

**Smartphone (please complete the following information):**

**Additional context**

**Comment by palexdev** [comment]
Can you provide the logs please?
1) Open the app
2) Try selecting the game
3) If nothing happens again close the app
4) Go into the AppData/Local/Temp directory
5) There should be a file named enbmanager.log
6) Upload it is a comment

**Comment by tian-li** [comment]
I did the steps you mentioned, and here is the log in screenshot and pasted
![image](https://github.com/palexdev/ENBManager/assets/11455447/8e3b357b-2e34-4d60-b024-882919b4aab4)
16:47:49.477: INFO  [JavaFX Application Thread] io.inverno.core.v1.Application - 
╭──────────────────────────────────────────────────────────────────────────────────╮
│ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿                                                       │
│ ⣿⣿⣿⣿⣿⣿⣿⠻⢿⠀⠀⡿⠟⣿⣿⣿⣿⣿⣿⣿ ENBManager                                            │
│ ⣿⣿⡿⠿⣿??⢹⣦⣄⠀⠀⣠⣴??⢹⣿⠿⢿⣿⣿    Version: 17.0.2                                    │
│ ⣿⣿⣷⣄⡀??⠘⢿⠙⠀⠀⠋⡿⠃⠈⢀⣠⣾⣿⣿    At: https://github.com/palexdev/ENBManager         │
│ ⣿⣿⣿??⣠⣴⡦⠀⢀⣶⣶⡀⠀⢴⣦⣄⣈⣿⣿⣿                                                       │
│ ⣿⣿⣿⡉⠙⠻⠗⠀⠈⠿⠿??⠀⠺⠟⠋⢉⣿⣿⣿ Powered by: Inverno Framework                         │
│ ⣿⣿⡿⠋??⡀⢠⣾⣠⠀⠀⣄⣷⡄⢀⠈⠙⢿⣿⣿    Version: 1.5.1                                     │
│ ⣿⣿⣷⣶⣿⣇⣸⠟⠋⠀⠀⠙⠻⣇⣸⣿⣶⣾⣿⣿    At: https://inverno.io                             │
│ ⣿⣿⣿⣿⣿⣿⣿⣴⣾⠀⠀⣷⣦⣿⣿⣿⣿⣿⣿⣿    Modules: [ENBManager.backend, ENBManager.frontend] │
│ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿                                                       │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────╮
│ Supported Games: │
│   - Skyrim       │
│   - Skyrim SE    │
╰──────────────────╯

16:47:50.030: INFO  [JavaFX Application Thread] io.inverno.core.v1.Application - Boostrap completed successfully!

**Comment by palexdev** [comment]
There are no errors in the log
What variant of the app are you using, binary or archive?

**Comment by tian-li** [comment]
Binary, downloaded from Nexus

**Comment by palexdev** [comment]
Can you try with the archive version and see if it works?

**Comment by tian-li** [comment]
Sure, I'll try tomorrow and let you know

**Comment by tian-li** [comment]
hmmm.... how to run archive version?

**Comment by palexdev** [comment]
In the bin folder there's a file named frontend.bat, double click and it should run

**Comment by tian-li** [comment]
archive version works

**Comment by palexdev** [comment]
Good
I think I'll deprecate the binary variant then
It is built with an experimental framework. It sure is more convenient and easy to use but it's too buggy and hard to debug on my end
